use serde::Serialize;
use std::fs;
use std::path::Path;

#[derive(Serialize)]
struct Post {
    slug: String,
    title: String,
    body: String,
}

fn content_dir() -> String {
    std::env::var("CONTENT_DIR").unwrap_or_else(|_| "content".into())
}

fn find_content() -> Vec<String> {
    walkdir::WalkDir::new(content_dir())
        .into_iter()
        .filter_map(|e| e.ok())
        .filter(|e| e.path().display().to_string().ends_with(".md"))
        .map(|e| e.path().display().to_string())
        .collect()
}

fn load_post(file: &str) -> Option<Post> {
    let markdown = fs::read_to_string(file).ok()?;
    let parser = pulldown_cmark::Parser::new_ext(&markdown, pulldown_cmark::Options::all());
    let mut body = String::new();
    pulldown_cmark::html::push_html(&mut body, parser);

    let slug = Path::new(file)
        .file_stem()
        .and_then(|s| s.to_str())
        .unwrap_or("")
        .to_owned();

    let title = slug.replace('-', " ").replace('_', " ");

    Some(Post { slug, title, body })
}

fn main() {
    let posts: Vec<Post> = find_content()
        .into_iter()
        .filter_map(|f| load_post(&f))
        .collect();

    #[derive(Serialize)]
    struct PostMeta<'a> { slug: &'a str, title: &'a str }
    let meta: Vec<PostMeta> = posts.iter()
        .map(|p| PostMeta { slug: &p.slug, title: &p.title })
        .collect();

    let posts_json = serde_json::to_string(&meta).unwrap();
    let by_slug_json = serde_json::to_string(
        &posts.iter().map(|p| (&p.slug, p)).collect::<std::collections::HashMap<_, _>>()
    ).unwrap();

    let output = format!(
        "// Auto-generated by api/ssg.rs — do not edit\n\
         export const posts = {};\n\
         export const postsBySlug: Record<string, {{ slug: string; title: string; body: string }}> = {};\n",
        posts_json, by_slug_json
    );

    fs::write("app/blog-data.server.ts", output).expect("failed to write blog-data.server.ts");
    println!("Generated {} posts into app/blog-data.server.ts", posts.len());
}
