use serde::Serialize;
use std::fs;
use std::path::Path;

#[derive(Serialize)]
struct Post {
    slug: String,
    title: String,
    body: String,
    date: String,
}

fn parse_frontmatter(content: &str) -> (Option<String>, String) {
    if !content.starts_with("---\n") {
        return (None, content.to_owned());
    }
    let rest = &content[4..];
    if let Some(end) = rest.find("\n---") {
        let frontmatter = &rest[..end];
        let date = frontmatter.lines().find_map(|line| {
            line.trim().strip_prefix("date:").map(|d| d.trim().to_owned())
        });
        let body = rest[end + 4..].trim_start_matches('\n').to_owned();
        (date, body)
    } else {
        (None, content.to_owned())
    }
}

fn content_dir() -> String {
    std::env::var("CONTENT_DIR").unwrap_or_else(|_| "content".into())
}

fn find_content() -> Vec<String> {
    walkdir::WalkDir::new(content_dir())
        .into_iter()
        .filter_map(|e| e.ok())
        .filter(|e| e.path().display().to_string().ends_with(".md"))
        .map(|e| e.path().display().to_string())
        .collect()
}

fn load_post(file: &str) -> Option<Post> {
    let content = fs::read_to_string(file).ok()?;
    let (date, markdown) = parse_frontmatter(&content);
    let parser = pulldown_cmark::Parser::new_ext(&markdown, pulldown_cmark::Options::all());
    let mut body = String::new();
    pulldown_cmark::html::push_html(&mut body, parser);

    let slug = Path::new(file)
        .file_stem()
        .and_then(|s| s.to_str())
        .unwrap_or("")
        .to_owned();

    let title = markdown
        .lines()
        .find_map(|line| line.strip_prefix("# ").map(|t| t.trim().to_owned()))
        .unwrap_or_else(|| slug.replace('-', " ").replace('_', " "));

    Some(Post { slug, title, body, date: date.unwrap_or_default() })
}

fn main() {
    let posts: Vec<Post> = find_content()
        .into_iter()
        .filter_map(|f| load_post(&f))
        .collect();

    #[derive(Serialize)]
    struct PostMeta<'a> { slug: &'a str, title: &'a str, date: &'a str }
    let meta: Vec<PostMeta> = posts.iter()
        .map(|p| PostMeta { slug: &p.slug, title: &p.title, date: &p.date })
        .collect();

    let posts_json = serde_json::to_string(&meta).unwrap();
    let by_slug_json = serde_json::to_string(
        &posts.iter().map(|p| (&p.slug, p)).collect::<std::collections::HashMap<_, _>>()
    ).unwrap();

    let output = format!(
        "// Auto-generated by api/ssg.rs — do not edit\n\
         export const posts = {};\n\
         export const postsBySlug: Record<string, {{ slug: string; title: string; body: string; date: string }}> = {};\n",
        posts_json, by_slug_json
    );

    fs::write("app/blog-data.server.ts", output).expect("failed to write blog-data.server.ts");
    println!("Generated {} posts into app/blog-data.server.ts", posts.len());
}
